vim.keymap.set('n', "<leader>wa",  vim.cmd.FlutterRun)
vim.keymap.set('n', "<leader>wt",  vim.cmd.FlutterTab)
vim.keymap.set('n', "<leader>wq",  vim.cmd.FlutterQuit)
vim.keymap.set('n', "<leader>wr",  vim.cmd.FlutterHotReload)
vim.keymap.set('n', "<leader>wR",  vim.cmd.FlutterHotRestart)
vim.keymap.set('n', "<leader>wD",  vim.cmd.FlutterVisualDebug)
